### Create new
POST {{url}}/tables
Content-Type: application/json
{
  "name": "costa-rica"
}
### Modify
PUT {{url}}/tables/4711
Content-Type: application/json
{
  "name": "costa-rica"
}
### Get all
GET {{url}}/tables
### Get single
GET {{url}}/tables/4711
### Delete
DELETE {{url}}/tables/4711